---
- hosts: all
  become: false
  user: vagrant
  vars:
    user: vagrant
    home: /home/vagrant/TF-Object-Detection-Tutorial
  tasks:
    - name: install basic tools
      become: true
      apt: pkg={{ item }} update_cache=yes state=latest
      with_items:
        - git
        - curl
        - build-essential
        - protobuf-compiler
        - python-pil
        - python-lxml
        - python-tk
        - python3-pip
      tags: apt

    - name: download tensorflow/models repository
      git:
        repo: "https://github.com/tensorflow/models.git"
        dest: "{{ home }}/models"
      tags: download

    - name: create python alias
      become: true
      file: state=link src=/usr/bin/python3.6 dest=/usr/bin/python
    - name: create pip3 alias
      become: true
      file: state=link src=/usr/bin/pip3 dest=/usr/bin/pip

    - name: install required python modules
      pip:
        requirements: "{{ home }}/requirements.txt"

    - name: download cocodataset/cocoapi repository
      git:
        repo: "https://github.com/cocodataset/cocoapi.git"
        dest: "{{ home }}/cocoapi"
      tags: cocoapi

    - name: install cocoapi
      shell: "{{ item }}"
      args:
        chdir: "{{ home }}/cocoapi/PythonAPI"
      with_items:
        - "make"
        - "cp -r {{ home }}/cocoapi/PythonAPI/pycocotools {{ home }}/models/research/"
      tags: cocoapi

    - name: porotobuf compilation
      shell: "protoc object_detection/protos/*.proto --python_out=."
      args:
        chdir: "{{ home }}/models/research/"

    - name: Add Libraries to PYTHONPATH
      shell: "echo \"export PYTHONPATH=$PYTHONPATH:{{ home }}/models/research/:{{ home }}/models/research/slim\" >> ~/.bash_profile"

    - name: Run test
      shell: /bin/bash -lc "python object_detection/builders/model_builder_test.py"
      args:
        chdir: "{{ home }}/models/research/"
      tags: last
